repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.0.0-alpha.1'
    hooks:
      - id: eslint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.8'
    hooks:
      - id: prettier
